"""Single-source every numeric claim in the paper from the result CSVs -> numbers.json.

The .tex draft reads these via \\newcommand macros, so no number is ever hand-typed into
the paper. Only four constants are taken from CHANGES.md / design (beta_learned,
declining_improvement_pct, n_locations, n_seasons); everything else is read from a CSV.
"""

from __future__ import annotations

import json
import os

import pandas as pd

HERE = os.path.dirname(__file__)
ROOT = os.path.abspath(os.path.join(HERE, ".."))
RES, TAB = os.path.join(ROOT, "results"), os.path.join(ROOT, "tables")


def _round(x, n=2):
    return round(float(x), n)


def build() -> dict:
    lb = pd.read_csv(os.path.join(RES, "leaderboard_v2.csv")).set_index("model")
    ph = pd.read_csv(os.path.join(RES, "phase_performance_v2.csv")).set_index("model")
    hb = pd.read_csv(os.path.join(RES, "horizon_breakdown.csv")).set_index("model")
    plc = pd.read_csv(os.path.join(RES, "per_location_coverage.csv"))
    sw = pd.read_csv(os.path.join(RES, "season_wis.csv"))
    dm = pd.read_csv(os.path.join(TAB, "dm_significance.csv"), index_col=0)

    d: dict = {
        "n_locations": 53,
        "n_seasons": 3,
        "beta_learned": 2.71,
        "declining_improvement_pct": 29,
        "mist_overall_wis": _round(lb.loc["mist_v2", "wis"]),
        "arima_overall_wis": _round(lb.loc["arima", "wis"]),
        "mist_cov95": _round(lb.loc["mist_v2", "cov_95"], 3),
        "mist_rising_wis": _round(ph.loc["mist_v2", "Rising"]),
        "arima_rising_wis": _round(ph.loc["arima", "Rising"]),
        "mist_peak_wis": _round(ph.loc["mist_v2", "Peak"]),
        "mist_declining_wis": _round(ph.loc["mist_v2", "Declining"]),
        "per_location_cov50_mean": _round(plc["cov_50"].mean(), 3),
        "per_location_cov50_std": _round(plc["cov_50"].std(), 3),
        "per_location_cov95_mean": _round(plc["cov_95"].mean(), 3),
        "mist_h4_wis": _round(hb.loc["mist_v2", "4"]),
        "arima_h4_wis": _round(hb.loc["arima", "4"]),
        "dm_p_vs_no_blend": float(dm.loc["mist_v2", "mist_no_blend"]),
        "dm_p_vs_no_mech": float(dm.loc["mist_v2", "mist_no_mech"]),
    }

    # ARIMA rising p: prefer the pooled 3-season table, else single-season.
    for fname in ("dm_headline_rising_3seasons.csv", "dm_headline_rising.csv"):
        fp = os.path.join(TAB, fname)
        if os.path.exists(fp):
            hr = pd.read_csv(fp)
            row = hr[hr["vs"] == "arima"]
            if not row.empty:
                d["dm_p_vs_arima_rising"] = float(row["p"].iloc[0])
                d["dm_p_vs_arima_rising_source"] = fname
                break

    # Per-season mist/arima WIS.
    piv = sw.pivot_table(index="season", columns="model", values="wis")
    for tag, season in [("2022", "2022-23"), ("2023", "2023-24"), ("2024", "2024-25")]:
        if season in piv.index:
            if "mist_v2" in piv.columns:
                d[f"season_{tag}_mist"] = _round(piv.loc[season, "mist_v2"], 1)
            if "arima" in piv.columns:
                d[f"season_{tag}_arima"] = _round(piv.loc[season, "arima"], 1)
    return d


# Map json keys -> LaTeX macro names (\newcommand). Only keys present are emitted.
_MACROS = {
    "n_locations": "nLoc", "n_seasons": "nSeasons", "beta_learned": "betaLearned",
    "declining_improvement_pct": "declImprove",
    "mist_overall_wis": "mistWIS", "arima_overall_wis": "arimaWIS",
    "mist_cov95": "mistCovNinetyfive",
    "mist_rising_wis": "mistRising", "arima_rising_wis": "arimaRising",
    "mist_peak_wis": "mistPeak", "mist_declining_wis": "mistDeclining",
    "per_location_cov50_mean": "covFiftyMean", "per_location_cov50_std": "covFiftyStd",
    "per_location_cov95_mean": "covNinetyfiveMean",
    "mist_h4_wis": "mistHfour", "arima_h4_wis": "arimaHfour",
    "dm_p_vs_no_blend": "dmBlend", "dm_p_vs_no_mech": "dmMech",
    "dm_p_vs_arima_rising": "dmArimaRising",
    "season_2022_mist": "seasonTwoTwoMist", "season_2022_arima": "seasonTwoTwoArima",
    "season_2023_mist": "seasonTwoThreeMist", "season_2023_arima": "seasonTwoThreeArima",
    "season_2024_mist": "seasonTwoFourMist", "season_2024_arima": "seasonTwoFourArima",
}


def _fmt_p(p: float) -> str:
    """Format a p-value for LaTeX prose."""
    if p < 1e-3:
        return f"{p:.0e}".replace("e-0", "\\times 10^{-").replace("e-", "\\times 10^{-") + "}"
    return f"{p:.3f}"


def _emit_macros(d: dict) -> str:
    lines = ["% Auto-generated by extract_numbers.py — DO NOT EDIT BY HAND.", ""]
    for key, macro in _MACROS.items():
        if key not in d:
            continue
        val = d[key]
        if key.startswith("dm_p_"):
            val = _fmt_p(float(val))
        lines.append(f"\\newcommand{{\\{macro}}}{{{val}}}")
    return "\n".join(lines) + "\n"


def run() -> dict:
    d = build()
    with open(os.path.join(HERE, "numbers.json"), "w") as f:
        json.dump(d, f, indent=2)
    with open(os.path.join(HERE, "macros.tex"), "w") as f:
        f.write(_emit_macros(d))
    print(json.dumps(d, indent=2))
    print(f"\nsaved -> {os.path.join(HERE, 'numbers.json')} + macros.tex")
    return d


if __name__ == "__main__":
    run()
